// DragonRealms weather prose — the full message corpus, machine-checked.
//
// Every sentence the game prints for weather, tagged with what it means. Two
// things make this worth a table instead of the regex ladder it replaces:
//
//   1. The SAME sentence means different things in different seasons. "It's
//      raining steadily." is severity 6 in spring but 7 in summer, so a matcher
//      that ignores the season grades a third of the corpus wrong.
//   2. Transitions carry a DIRECTION. "The rain slacks off somewhat." and "The
//      rain begins to come down more heavily." land on the same severity from
//      opposite sides, which is what lets the panel show a trend arrow.
//
// Columns: [text, region, season, severity, kind, kind-of-line, direction, time, stars]
//   text      normalized match key (see normalize() in weather.ts — keep in step)
//   region    'standard' (most of Elanthia) | 'muspari' (the Muspar'i desert)
//   season    'any' matches every season
//   severity  0-9 on the game's own scale: 0-4 sky conditions (clear -> overcast),
//             5-9 precipitation. Muspar'i escalates into blowing sand from 3.
//   kind      what to draw: clear | rain | snow | dust
//   line      'state' (a report of how things are) | 'transition' (a change)
//   direction 'improving' | 'worsening' on transitions; null on states
//   time      'day' | 'night' | 'any' — some prose only appears at one
//   stars     'none' | 'diminished' | 'normal' — star visibility, when the line says
//
// Reference: https://elanthipedia.play.net/Weather

import type { WeatherRow } from './weather'

export const WEATHER_TABLE: WeatherRow[] = [
  ["night winter sky is a hollow, vacant black", 'standard', 'winter', 1, 'clear', 'state', null, 'night', 'none'],
  ["night winter sky is studded with hesitant stars", 'standard', 'winter', 1, 'clear', 'state', null, 'night', 'diminished'],
  ["night winter sky is a crisp, clear, starry black", 'standard', 'winter', 1, 'clear', 'state', null, 'night', 'normal'],
  ["sky is a sharp, clear blue", 'standard', 'winter', 1, 'clear', 'state', null, 'day', null],
  ["last few clouds drift away, leaving behind a ebon expanse", 'standard', 'winter', 1, 'clear', 'transition', 'improving', 'night', 'none'],
  ["last few clouds drift away, leaving a smattering of stars", 'standard', 'winter', 1, 'clear', 'transition', 'improving', 'night', 'diminished'],
  ["last few clouds drift away, leaving a fine expanse of stars", 'standard', 'winter', 1, 'clear', 'transition', 'improving', 'night', 'normal'],
  ["last of the grey clouds drift away to reveal a crisp blue sky", 'standard', 'winter', 1, 'clear', 'transition', 'improving', 'day', null],
  ["ebon sky above is marred by a few dark clouds", 'standard', 'winter', 2, 'clear', 'state', null, 'night', 'none'],
  ["remaining stars above are marred by a few dark clouds", 'standard', 'winter', 2, 'clear', 'state', null, 'night', 'diminished'],
  ["starry skies above are marred by a few dark clouds", 'standard', 'winter', 2, 'clear', 'state', null, 'night', 'normal'],
  ["sky has a few cold, grey clouds lurking in its heights", 'standard', 'winter', 2, 'clear', 'state', null, 'day', null],
  ["most of the clouds drift away to reveal a hollow sky", 'standard', 'winter', 2, 'clear', 'transition', 'improving', 'night', 'none'],
  ["most of the clouds drift away to reveal the remaining stars", 'standard', 'winter', 2, 'clear', 'transition', 'improving', 'night', 'diminished'],
  ["most of the clouds drift away to reveal a fine expanse of stars", 'standard', 'winter', 2, 'clear', 'transition', 'improving', 'night', 'normal'],
  ["most of the clouds above drift away on a chill winter breeze", 'standard', 'winter', 2, 'clear', 'transition', 'improving', 'day', null],
  ["few clouds drift past, partially obscuring the sky", 'standard', 'winter', 2, 'clear', 'transition', 'worsening', 'night', 'none'],
  ["few clouds drift past, obscuring most of the remaining stars", 'standard', 'winter', 2, 'clear', 'transition', 'worsening', 'night', 'diminished'],
  ["few clouds drift past, partially obscuring the stars", 'standard', 'winter', 2, 'clear', 'transition', 'worsening', 'night', 'normal'],
  ["few cold, grey clouds drift into the sky", 'standard', 'winter', 2, 'clear', 'transition', 'worsening', 'day', null],
  ["dark clouds of grey obscure the hollow sky above", 'standard', 'winter', 3, 'clear', 'state', null, 'night', 'none'],
  ["dark clouds of grey obscure most of the remaining stars", 'standard', 'winter', 3, 'clear', 'state', null, 'night', 'diminished'],
  ["dark clouds of grey obscure most of the stars above", 'standard', 'winter', 3, 'clear', 'state', null, 'night', 'normal'],
  ["sky is nearly filled with cold, grey clouds", 'standard', 'winter', 3, 'clear', 'state', null, 'day', null],
  ["clouds break slightly, revealing a hollow, black sky", 'standard', 'winter', 3, 'clear', 'transition', 'improving', 'night', 'none'],
  ["clouds break slightly, revealing a small handful of stars", 'standard', 'winter', 3, 'clear', 'transition', 'improving', 'night', 'diminished'],
  ["clouds break slightly, revealing a few twinkling stars", 'standard', 'winter', 3, 'clear', 'transition', 'improving', 'night', 'normal'],
  ["cold, grey bank of clouds above parts slightly", 'standard', 'winter', 3, 'clear', 'transition', 'improving', 'day', null],
  ["more clouds drift in, obscuring the night sky", 'standard', 'winter', 3, 'clear', 'transition', 'worsening', 'night', 'none'],
  ["more clouds drift in, obscuring the remaining stars", 'standard', 'winter', 3, 'clear', 'transition', 'worsening', 'night', 'diminished'],
  ["more clouds drift in, obscuring most of the stars", 'standard', 'winter', 3, 'clear', 'transition', 'worsening', 'night', 'normal'],
  ["large grey clouds move in, obscuring most of the sky above", 'standard', 'winter', 3, 'clear', 'transition', 'worsening', 'day', null],
  ["thick bank of clouds obscures the heavens", 'standard', 'winter', 4, 'clear', 'state', null, 'night', null],
  ["thick bank of grey clouds fills the sky from horizon to horizon", 'standard', 'winter', 4, 'clear', 'state', null, 'day', null],
  ["snow stops, leaving the night a cold, frozen black", 'standard', 'winter', 4, 'snow', 'transition', 'improving', 'night', null],
  ["snow stops, leaving only an overcast sky of grey", 'standard', 'winter', 4, 'snow', 'transition', 'improving', 'day', null],
  ["last of the sky above disappears behind a sheaf of clouds", 'standard', 'winter', 4, 'clear', 'transition', 'worsening', 'night', 'none'],
  ["last of the stars above disappears behind a thick sheaf of clouds", 'standard', 'winter', 4, 'clear', 'transition', 'worsening', 'night', 'normal'],
  ["sky becomes completely overcast", 'standard', 'winter', 4, 'clear', 'transition', 'worsening', 'day', null],
  ["sky becomes completely overcast", 'standard', 'spring', 4, 'clear', 'transition', 'worsening', 'any', null],
  ["light snow is falling", 'standard', 'winter', 5, 'snow', 'state', null, 'any', null],
  ["snow lessens to a light flurry", 'standard', 'winter', 5, 'snow', 'transition', 'improving', 'any', null],
  ["light snow begins to fall from the sky", 'standard', 'winter', 5, 'snow', 'transition', 'worsening', 'any', null],
  ["snow is falling steadily", 'standard', 'winter', 6, 'snow', 'state', null, 'any', null],
  ["snow slacks off to a moderate flurry", 'standard', 'winter', 6, 'snow', 'transition', 'improving', 'any', null],
  ["snow begins to fall more heavily", 'standard', 'winter', 6, 'snow', 'transition', 'worsening', 'any', null],
  ["snow is falling heavily", 'standard', 'winter', 7, 'snow', 'state', null, 'any', null],
  ["snow slackens somewhat", 'standard', 'winter', 7, 'snow', 'transition', 'improving', 'any', null],
  ["snowfall grows very heavy", 'standard', 'winter', 7, 'snow', 'transition', 'worsening', 'any', null],
  ["it's a blizzard", 'standard', 'winter', 8, 'snow', 'state', null, 'any', null],
  ["snow reduces in intensity slightly", 'standard', 'winter', 8, 'snow', 'transition', 'improving', 'any', null],
  ["snow increases in severity and is now a blizzard", 'standard', 'winter', 8, 'snow', 'transition', 'worsening', 'any', null],
  ["sky is clear", 'standard', 'spring', 1, 'clear', 'state', null, 'any', null],
  ["last few clouds clear away, leaving an open sky", 'standard', 'spring', 1, 'clear', 'transition', 'improving', 'any', null],
  ["sky has a few scattered clouds in it", 'standard', 'spring', 2, 'clear', 'state', null, 'any', null],
  ["clouds break up somewhat, leaving only a few left in the sky", 'standard', 'spring', 2, 'clear', 'transition', 'improving', 'any', null],
  ["few fluffy clouds move into the sky", 'standard', 'spring', 2, 'clear', 'transition', 'worsening', 'any', null],
  ["sky is very cloudy", 'standard', 'spring', 3, 'clear', 'state', null, 'any', null],
  ["clouds part slightly, revealing bits of open sky", 'standard', 'spring', 3, 'clear', 'transition', 'improving', 'any', null],
  ["more clouds move in above, almost obscuring the sky completely", 'standard', 'spring', 3, 'clear', 'transition', 'worsening', 'any', null],
  ["more clouds move in above, almost obscuring the sky completely", 'standard', 'summer', 4, 'clear', 'transition', 'worsening', 'any', null],
  ["more clouds move in above, almost obscuring the sky completely", 'standard', 'autumn', 3, 'clear', 'transition', 'worsening', 'any', null],
  ["it is completely overcast", 'standard', 'spring', 4, 'clear', 'state', null, 'any', null],
  ["rain stops, leaving only an overcast sky", 'standard', 'spring', 4, 'rain', 'transition', 'improving', 'any', null],
  ["rain stops, leaving only an overcast sky", 'standard', 'summer', 5, 'rain', 'transition', 'improving', 'any', null],
  ["rain stops, leaving only an overcast sky", 'standard', 'autumn', 4, 'rain', 'transition', 'improving', 'any', null],
  ["it is drizzling", 'standard', 'spring', 5, 'rain', 'state', null, 'any', null],
  ["rain lessens somewhat to a dull drizzle", 'standard', 'spring', 5, 'rain', 'transition', 'improving', 'any', null],
  ["light rain begins to fall from the sky", 'standard', 'spring', 5, 'rain', 'transition', 'worsening', 'any', null],
  ["it's raining steadily", 'standard', 'spring', 6, 'rain', 'state', null, 'any', null],
  ["it's raining steadily", 'standard', 'summer', 7, 'rain', 'state', null, 'any', null],
  ["rain slacks off somewhat", 'standard', 'spring', 6, 'rain', 'transition', 'improving', 'any', null],
  ["rain slacks off somewhat", 'standard', 'summer', 7, 'rain', 'transition', 'improving', 'any', null],
  ["rain begins to come down more heavily", 'standard', 'spring', 6, 'rain', 'transition', 'worsening', 'any', null],
  ["rain begins to come down more heavily", 'standard', 'summer', 7, 'rain', 'transition', 'worsening', 'any', null],
  ["it's raining heavily under a stormy sky", 'standard', 'spring', 7, 'rain', 'state', null, 'any', null],
  ["rain slackens off to a heavy downpour", 'standard', 'spring', 7, 'rain', 'transition', 'improving', 'any', null],
  ["rain slackens off to a heavy downpour", 'standard', 'summer', 8, 'rain', 'transition', 'improving', 'any', null],
  ["rain slackens off to a heavy downpour", 'standard', 'autumn', 7, 'rain', 'transition', 'improving', 'any', null],
  ["steady rains turn into a driving storm", 'standard', 'spring', 7, 'rain', 'transition', 'worsening', 'any', null],
  ["rain is pouring from the sky in a driving squall", 'standard', 'spring', 8, 'rain', 'state', null, 'any', null],
  ["rain reduces in intensity slightly", 'standard', 'spring', 8, 'rain', 'transition', 'improving', 'any', null],
  ["rain reduces in intensity slightly", 'standard', 'autumn', 8, 'rain', 'transition', 'improving', 'any', null],
  ["storm increases in strength to a ferocious squall", 'standard', 'spring', 8, 'rain', 'transition', 'worsening', 'any', null],
  ["driving rain falls in fierce sheets, stinging like a thousand lashes", 'standard', 'spring', 9, 'rain', 'state', null, 'any', null],
  ["driving rain falls in fierce sheets, stinging like a thousand lashes", 'standard', 'autumn', 9, 'rain', 'state', null, 'any', null],
  ["fearsome storm reduces in intensity slightly", 'standard', 'spring', 9, 'clear', 'transition', 'improving', 'any', null],
  ["fearsome storm reduces in intensity slightly", 'standard', 'autumn', 9, 'clear', 'transition', 'improving', 'any', null],
  ["storm increases in strength, scourging elanthia like the wrath of an angry god", 'standard', 'spring', 9, 'clear', 'transition', 'worsening', 'any', null],
  ["storm increases in strength, scourging elanthia like the wrath of an angry god", 'standard', 'autumn', 9, 'clear', 'transition', 'worsening', 'any', null],
  ["limitless black expanse stretches out across the clear sky", 'standard', 'summer', 1, 'clear', 'state', null, 'night', 'none'],
  ["patchwork of stars shine down from an exceptionally clear sky", 'standard', 'summer', 1, 'clear', 'state', null, 'night', 'diminished'],
  ["thousands of brilliant stars shine in an exceptionally clear sky", 'standard', 'summer', 1, 'clear', 'state', null, 'night', 'normal'],
  ["hot summer sun blazes from its perch in a cloudless sky", 'standard', 'summer', 1, 'clear', 'state', null, 'day', null],
  ["gentle summer breeze warms the air", 'standard', 'summer', 1, 'clear', 'transition', 'improving', 'night', null],
  ["heat from the sun grows rather intense", 'standard', 'summer', 1, 'clear', 'transition', 'improving', 'day', null],
  ["clear summertime sky is black and devoid of stars", 'standard', 'summer', 2, 'clear', 'state', null, 'night', 'none'],
  ["clear summertime sky glimmers feebly with a patchwork of stars", 'standard', 'summer', 2, 'clear', 'state', null, 'night', 'diminished'],
  ["clear summertime sky shines with many twinkling stars", 'standard', 'summer', 2, 'clear', 'state', null, 'night', 'normal'],
  ["sky above is a bright blue, and free of clouds", 'standard', 'summer', 2, 'clear', 'state', null, 'day', null],
  ["last few clouds drift away to reveal a black and hollow sky", 'standard', 'summer', 2, 'clear', 'transition', 'improving', 'night', 'none'],
  ["last few clouds drift away to reveal a handful for stars", 'standard', 'summer', 2, 'clear', 'transition', 'improving', 'night', 'diminished'],
  ["last few clouds drift away to reveal a sky full of twinkling stars", 'standard', 'summer', 2, 'clear', 'transition', 'improving', 'night', 'normal'],
  ["last few clouds drift away to reveal a sky full of twinkling stars", 'standard', 'autumn', 1, 'clear', 'transition', 'improving', 'night', 'normal'],
  ["last few clouds in the sky above slowly drift away", 'standard', 'summer', 2, 'clear', 'transition', 'improving', 'day', null],
  ["last few clouds in the sky above slowly drift away", 'standard', 'autumn', 1, 'clear', 'transition', 'improving', 'day', null],
  ["wind shifts slightly, cooling the night air", 'standard', 'summer', 2, 'clear', 'transition', 'worsening', 'night', null],
  ["winds shift slightly to bring respite from the hot sun", 'standard', 'summer', 2, 'clear', 'transition', 'worsening', 'day', null],
  ["few scattered clouds obscure the hollow sky", 'standard', 'summer', 3, 'clear', 'state', null, 'night', 'none'],
  ["few scattered clouds obscure the remaining stars", 'standard', 'summer', 3, 'clear', 'state', null, 'night', 'diminished'],
  ["few scattered clouds obscure some of the stars above", 'standard', 'summer', 3, 'clear', 'state', null, 'night', 'normal'],
  ["few white clouds float lazily in the sky above", 'standard', 'summer', 3, 'clear', 'state', null, 'day', null],
  ["few white clouds float lazily in the sky above", 'standard', 'autumn', 2, 'clear', 'state', null, 'day', null],
  ["most of the clouds drift away to reveal a sky devoid of stars", 'standard', 'summer', 3, 'clear', 'transition', 'improving', 'night', 'none'],
  ["most of the clouds drift away to reveal feebly glistening stars", 'standard', 'summer', 3, 'clear', 'transition', 'improving', 'night', 'diminished'],
  ["most of the clouds drift away to reveal starry skies above", 'standard', 'summer', 3, 'clear', 'transition', 'improving', 'night', 'normal'],
  ["breeze high in the skies above gently blows most of the clouds away", 'standard', 'summer', 3, 'clear', 'transition', 'improving', 'day', null],
  ["few clouds drift by, obscuring the hollow sky as they pass", 'standard', 'summer', 3, 'clear', 'transition', 'worsening', 'night', 'none'],
  ["fwe clouds drift by, obscuring the feeble stars as they pass", 'standard', 'summer', 3, 'clear', 'transition', 'worsening', 'night', 'diminished'],
  ["few clouds drift by, obscuring the stars as they pass", 'standard', 'summer', 3, 'clear', 'transition', 'worsening', 'night', 'normal'],
  ["few clouds drift by, obscuring the stars as they pass", 'standard', 'autumn', 2, 'clear', 'transition', 'worsening', 'night', 'normal'],
  ["few fluffy white clouds drift into the sky above", 'standard', 'summer', 3, 'clear', 'transition', 'worsening', 'day', null],
  ["few fluffy white clouds drift into the sky above", 'standard', 'autumn', 2, 'clear', 'transition', 'worsening', 'day', null],
  ["thick clouds dominate the sky above", 'standard', 'summer', 4, 'clear', 'state', null, 'night', 'none'],
  ["thick clouds above obscure all but a few lucky stars", 'standard', 'summer', 4, 'clear', 'state', null, 'night', 'normal'],
  ["it's quite cloudy and a bit muggy", 'standard', 'summer', 4, 'clear', 'state', null, 'day', null],
  ["clouds part slightly, revealing slivers of an ebon void", 'standard', 'summer', 4, 'clear', 'transition', 'improving', 'night', 'none'],
  ["clouds part slightly, revealing a few feeble stars", 'standard', 'summer', 4, 'clear', 'transition', 'improving', 'night', 'diminished'],
  ["clouds part slightly, revealing a few twinkling stars", 'standard', 'summer', 4, 'clear', 'transition', 'improving', 'night', 'normal'],
  ["clouds part slightly, revealing a few twinkling stars", 'standard', 'autumn', 3, 'clear', 'transition', 'improving', 'night', 'normal'],
  ["clouds part slightly to reveal patches of blue sky", 'standard', 'summer', 4, 'clear', 'transition', 'improving', 'day', null],
  ["clouds part slightly to reveal patches of blue sky", 'standard', 'autumn', 3, 'clear', 'transition', 'improving', 'day', null],
  ["dark clouds obscure the night sky above", 'standard', 'summer', 5, 'clear', 'state', null, 'night', null],
  ["dark clouds obscure the night sky above", 'standard', 'autumn', 4, 'clear', 'state', null, 'night', null],
  ["sky is completely covered with clouds", 'standard', 'summer', 5, 'clear', 'state', null, 'day', null],
  ["sky is completely covered with clouds", 'standard', 'autumn', 4, 'clear', 'state', null, 'day', null],
  ["large, black clouds slowly cover the skies", 'standard', 'summer', 5, 'clear', 'transition', 'worsening', 'night', 'none'],
  ["large, black clouds slowly cover the skies", 'standard', 'autumn', 4, 'clear', 'transition', 'worsening', 'night', 'none'],
  ["last of the stars disappear behind a thick bank of clouds", 'standard', 'summer', 5, 'clear', 'transition', 'worsening', 'night', 'normal'],
  ["large, grey clouds slowly cover the skies", 'standard', 'summer', 5, 'clear', 'transition', 'worsening', 'day', null],
  ["large, grey clouds slowly cover the skies", 'standard', 'autumn', 4, 'clear', 'transition', 'worsening', 'day', null],
  ["light rain patters silently down from dark skies above", 'standard', 'summer', 6, 'rain', 'state', null, 'night', null],
  ["light rain patters silently down from dark skies above", 'standard', 'autumn', 5, 'rain', 'state', null, 'night', null],
  ["gentle summer rain patters to the earth around you", 'standard', 'summer', 6, 'rain', 'state', null, 'day', null],
  ["steady rains lessen to a gentle summer shower", 'standard', 'summer', 6, 'rain', 'transition', 'improving', 'any', null],
  ["light rain begins to patter down from above", 'standard', 'summer', 6, 'rain', 'transition', 'worsening', 'any', null],
  ["light rain begins to patter down from above", 'standard', 'autumn', 5, 'rain', 'transition', 'worsening', 'any', null],
  ["it's raining heavily", 'standard', 'summer', 8, 'rain', 'state', null, 'any', null],
  ["it's raining heavily", 'standard', 'autumn', 7, 'rain', 'state', null, 'any', null],
  ["rain falls harder and is now a heavy downpour", 'standard', 'summer', 8, 'rain', 'transition', 'worsening', 'any', null],
  ["rain falls harder and is now a heavy downpour", 'standard', 'autumn', 7, 'rain', 'transition', 'worsening', 'any', null],
  ["sky is a hollow, vacant black", 'standard', 'autumn', 1, 'clear', 'state', null, 'night', 'none'],
  ["patchwork of stars sputter in the clear autmn skies", 'standard', 'autumn', 1, 'clear', 'state', null, 'night', 'diminished'],
  ["thousands of stars twinkle merrily from clear autumn skies", 'standard', 'autumn', 1, 'clear', 'state', null, 'night', 'normal'],
  ["autumn sky above is a bright, cheery blue", 'standard', 'autumn', 1, 'clear', 'state', null, 'day', null],
  ["last few clouds drift away to reveal an empty expanse", 'standard', 'autumn', 1, 'clear', 'transition', 'improving', 'night', 'none'],
  ["last few clouds drift away to reveal the remaining stars", 'standard', 'autumn', 1, 'clear', 'transition', 'improving', 'night', 'diminished'],
  ["few scattered clouds drift in the night skies above", 'standard', 'autumn', 2, 'clear', 'state', null, 'night', null],
  ["most of the clouds drift away to reveal an empty sky", 'standard', 'autumn', 2, 'clear', 'transition', 'improving', 'night', 'none'],
  ["most of the clouds drift away to reveal a few, lonely stars", 'standard', 'autumn', 2, 'clear', 'transition', 'improving', 'night', 'diminished'],
  ["most of the clouds drift away to reveal starry skies", 'standard', 'autumn', 2, 'clear', 'transition', 'improving', 'night', 'normal'],
  ["most of the clouds blow away on a cool, gentle breeze", 'standard', 'autumn', 2, 'clear', 'transition', 'improving', 'day', null],
  ["few clouds drift by, obscuring the empty sky as they pass", 'standard', 'autumn', 2, 'clear', 'transition', 'worsening', 'night', 'none'],
  ["few clouds drift by, concealing much of the remaining starlight", 'standard', 'autumn', 2, 'clear', 'transition', 'worsening', 'night', 'diminished'],
  ["thick clouds obscure nearly the entire sky", 'standard', 'autumn', 3, 'clear', 'state', null, 'night', 'none'],
  ["thick clouds obscure nearly all the remaining stars", 'standard', 'autumn', 3, 'clear', 'state', null, 'night', 'diminished'],
  ["thick clouds above obscure nearly all of the stars", 'standard', 'autumn', 3, 'clear', 'state', null, 'night', 'normal'],
  ["thick bank of clouds obscures nearly all of the sky above", 'standard', 'autumn', 3, 'clear', 'state', null, 'day', null],
  ["clouds part slightly, revealing an ebon void above", 'standard', 'autumn', 3, 'clear', 'transition', 'improving', 'night', 'none'],
  ["clouds part slightly, revealing a few guttering stars", 'standard', 'autumn', 3, 'clear', 'transition', 'improving', 'night', 'diminished'],
  ["last of the stars disappear behind a bank of grey clouds", 'standard', 'autumn', 4, 'clear', 'transition', 'worsening', 'night', 'normal'],
  ["light autumn rain patters to the earth around you", 'standard', 'autumn', 5, 'rain', 'state', null, 'day', null],
  ["steady rains lessen to a light, misty drizzle", 'standard', 'autumn', 5, 'rain', 'transition', 'improving', 'any', null],
  ["steady rain falls from dark skies above", 'standard', 'autumn', 6, 'rain', 'state', null, 'any', null],
  ["heavy rains lessen to a steady shower", 'standard', 'autumn', 6, 'rain', 'transition', 'improving', 'any', null],
  ["rain begins to come down even more heavily", 'standard', 'autumn', 6, 'rain', 'transition', 'worsening', 'any', null],
  ["it's raining a downpour", 'standard', 'autumn', 8, 'rain', 'state', null, 'any', null],
  ["rain increases in severity and is now a severe downpour", 'standard', 'autumn', 8, 'rain', 'transition', 'worsening', 'any', null],
  ["sky is completely clear", 'standard', 'any', 0, 'clear', 'state', null, 'any', null],
  ["cold expanse of darkness stretches across the horizon", 'muspari', 'any', 1, 'clear', 'state', null, 'night', 'none'],
  ["remaining stars glitter brilliantly in the perfectly clear sky", 'muspari', 'any', 1, 'clear', 'state', null, 'night', 'diminished'],
  ["thousands of diamond pointed stars glitter brilliantly in an exceptionally clear sky", 'muspari', 'any', 1, 'clear', 'state', null, 'night', 'normal'],
  ["dazzling sapphire sky frames the blazing jewel of the golden sun", 'muspari', 'any', 1, 'clear', 'state', null, 'day', null],
  ["unbroken expanse of azure sky allows no relief from the torrid touch of the burning sun", 'muspari', 'any', 1, 'clear', 'state', null, 'day', null],
  ["blazing sun turns crystalline skies incandescent with shimmering bands of translucent heat", 'muspari', 'any', 1, 'clear', 'state', null, 'day', null],
  ["few stars twinkle in the velvet night sky", 'muspari', 'any', 1, 'clear', 'transition', 'improving', 'night', 'diminished'],
  ["multitude of stars twinkle from the velvet night sky, their clear light warding the soul from the odd chill of the night air", 'muspari', 'any', 1, 'clear', 'transition', 'improving', 'night', 'normal'],
  ["dusky gold image of the sun seems a watery mirage as it wavers in shimmering ripples of heat reflected from the ground", 'muspari', 'any', 1, 'clear', 'transition', 'improving', 'day', null],
  ["tentative strands of gossamer clouds writhe agonizingly before dissipating under the relentless assault of the sun", 'muspari', 'any', 1, 'clear', 'transition', 'improving', 'day', null],
  ["light purple haze colors the otherwise starkly black night", 'muspari', 'any', 2, 'clear', 'state', null, 'night', 'none'],
  ["light purple haze threatens to overwhelm the faded starlight", 'muspari', 'any', 2, 'clear', 'state', null, 'night', 'diminished'],
  ["light purple haze only accentuates the soft sparkle of starlight", 'muspari', 'any', 2, 'clear', 'state', null, 'night', 'normal'],
  ["feathery streamers of high gossamer clouds race swiftly towards the horizon, fleeing the stern gaze of the sun", 'muspari', 'any', 2, 'clear', 'state', null, 'day', null],
  ["faint dust veil shrouds the sun in a hazy glow, intensifying the sweltering heat", 'muspari', 'any', 2, 'clear', 'state', null, 'day', null],
  ["delicate tracings of dust swirls streak the harsh blue sky, softening the edges of the sun's glare", 'muspari', 'any', 2, 'clear', 'state', null, 'day', null],
  ["fitful breeze pauses, settling the dust in the air and revealing an ebon void where the stars should be", 'muspari', 'any', 2, 'clear', 'transition', 'improving', 'night', 'none'],
  ["fitful breeze pauses, settling the dust in the air and revealing a handful of faint stars", 'muspari', 'any', 2, 'clear', 'transition', 'improving', 'night', 'diminished'],
  ["fitful breeze pauses, the dusting in the air settling to reveal the midnight velvet sky holding a dragon's hoard of crystalline stars", 'muspari', 'any', 2, 'clear', 'transition', 'improving', 'night', 'normal'],
  ["translucent dust veils shrouding the sun hang in tattered ribbons as though clawed by one of the prydaen guardians", 'muspari', 'any', 2, 'clear', 'transition', 'improving', 'day', null],
  ["dusty haze whipped up by the breeze settles with a soft, tentative sigh to reveal the burnished gold of the sun", 'muspari', 'any', 2, 'clear', 'transition', 'improving', 'day', null],
  ["wind shifts slightly, chilling the night air with a death kiss", 'muspari', 'any', 2, 'clear', 'transition', 'worsening', 'night', null],
  ["sweltering heat slicks from irritated wind gusts like a belch from a volcano's torrid center", 'muspari', 'any', 2, 'clear', 'transition', 'worsening', 'day', null],
  ["inferno of smoky heat and dust swirl across the inhospitable landscape, intent on some arcane task", 'muspari', 'any', 2, 'clear', 'transition', 'worsening', 'day', null],
  ["low haze of swirling sand obstructs most of the night sky", 'muspari', 'any', 3, 'dust', 'state', null, 'night', null],
  ["fitful wind smudges the sky in a rainbow of prismatic colors almost obscuring the sun in a cloak of dust and sand", 'muspari', 'any', 3, 'dust', 'state', null, 'day', null],
  ["swirled sand dances to the wild melody of the wind under the blazing bronze heat of the obscured sun", 'muspari', 'any', 3, 'dust', 'state', null, 'day', null],
  ["few determined sunbeams flicker through the pervasive haze of the dusty air", 'muspari', 'any', 3, 'clear', 'state', null, 'day', null],
  ["winds slacken, revealing a hollow sky behind airborne dust", 'muspari', 'any', 3, 'dust', 'transition', 'improving', 'night', 'none'],
  ["winds slacken, revealing a handful of guttering stars behind the cloak of dust", 'muspari', 'any', 3, 'dust', 'transition', 'improving', 'night', 'diminished'],
  ["fitful winds slacken, revealing star-filled skies behind the cloak of dust", 'muspari', 'any', 3, 'dust', 'transition', 'improving', 'night', 'normal'],
  ["steel-grey skies lighten to blues tinged with narrow streaks of tangerine as the harsh wind stays its hand", 'muspari', 'any', 3, 'clear', 'transition', 'improving', 'day', null],
  ["veiling the horizon from view, the rippling heat smears the skyline into bands of smoky blue and grey watercolors", 'muspari', 'any', 3, 'clear', 'transition', 'improving', 'day', null],
  ["bored winds kick up high swirls of gritty sand that hide the night sky", 'muspari', 'any', 3, 'dust', 'transition', 'worsening', 'night', null],
  ["golden veils of sand sway and dart gracefully over the land, mesmerized by the compelling melody of the wind", 'muspari', 'any', 3, 'dust', 'transition', 'worsening', 'day', null],
  ["hazy clouds of gritty sand swirl, pulling the sun's heat over you in a suffocating blanket", 'muspari', 'any', 3, 'dust', 'transition', 'worsening', 'day', null],
  ["harsh clouds of gritty sand obscure the sky", 'muspari', 'any', 4, 'dust', 'state', null, 'night', 'none'],
  ["harsh clouds of gritty sand obscure all but a few lucky stars", 'muspari', 'any', 4, 'dust', 'state', null, 'night', 'normal'],
  ["languorous heat of the air drapes heavily across the shoulders of the land in a stifling boa of oppressive stillness", 'muspari', 'any', 4, 'clear', 'state', null, 'day', null],
  ["glowering skies dense with particles of sand seem to swirl and snap in the fitful wind like a trapped wild beast", 'muspari', 'any', 4, 'dust', 'state', null, 'day', null],
  ["dust clouds part slightly, revealing an ebon expanse", 'muspari', 'any', 4, 'dust', 'transition', 'improving', 'night', 'none'],
  ["dust clouds part slightly, revealing a few twinkling stars", 'muspari', 'any', 4, 'dust', 'transition', 'improving', 'night', 'normal'],
  ["oppressive heat saps the energy of the cruel winds kicking up an apathetic spray of grit along the horizon", 'muspari', 'any', 4, 'dust', 'transition', 'improving', 'day', null],
  ["winds drop suddenly, leaving glowering skies and sweltering air that make breathing an effort", 'muspari', 'any', 4, 'clear', 'transition', 'improving', 'day', null],
  ["thick dust in the air creates prisms casting sudden glorious rainbows that paint the lands with the colors of the gods", 'muspari', 'any', 4, 'dust', 'transition', 'worsening', 'any', null],
  ["hot, arid air sucks voraciously upon any suggestion of moisture, draining every bit from the landscape below", 'muspari', 'any', 4, 'clear', 'transition', 'worsening', 'any', null],
  ["ominous chill wind scratches over skin as dust veils obscure the stars", 'muspari', 'any', 5, 'dust', 'state', null, 'night', null],
  ["sporadic wind listlessly kicks up eddies of tired dust and dirt", 'muspari', 'any', 5, 'dust', 'state', null, 'day', null],
  ["brisk flutters of irritated air pluck restlessly at the ground, spinning dust and debris into small vortexes", 'muspari', 'any', 5, 'dust', 'state', null, 'day', null],
  ["torrid heat crystallizes the dusty air, making every indrawn breath a difficult burden", 'muspari', 'any', 5, 'clear', 'transition', 'improving', 'any', null],
  ["bits of sharp quartz and grit abrade your face as the breeze quickens momentarily to a gust of driving wind", 'muspari', 'any', 5, 'dust', 'transition', 'improving', 'any', null],
  ["heavy darkness surrounds you as oppressive heat rises off the desert floor to thickly swaddle you in a sticky cloak", 'muspari', 'any', 5, 'clear', 'transition', 'worsening', 'night', null],
  ["particles of sand and dust pelt you as they are swept into the skies by gusting winds", 'muspari', 'any', 5, 'dust', 'transition', 'worsening', 'day', null],
  ["tumultuous cloud of dust and sand fills the horizon, jagged flashes of heat lightning illuminating the clouds from within", 'muspari', 'any', 5, 'dust', 'transition', 'worsening', 'day', null],
  ["chill fingers of night breezes tap grittily over flesh in an abrasive caress", 'muspari', 'any', 6, 'dust', 'state', null, 'night', null],
  ["wind's corpse fingers stroke longingly with a gritty touch over your cheek", 'muspari', 'any', 6, 'dust', 'state', null, 'day', null],
  ["coils of twisting wind burdened by heavy cloaks of grey sand and dust writhe like intertwining snakes over the flat grey sky", 'muspari', 'any', 6, 'dust', 'state', null, 'day', null],
  ["heat lightning flickers wildly over the smudged line of the horizon, seeming to only increase the suffocating heat with impotent flashes", 'muspari', 'any', 6, 'clear', 'state', null, 'day', null],
  ["angry wind tosses handfuls of heavy grit into the air like an indulged child in an emotional tantrum, allowing only a dim view of the horizon", 'muspari', 'any', 6, 'dust', 'transition', 'improving', 'any', null],
  ["murderous shriek of the caterwauling wind ceases abruptly for a few heartbeats before resuming", 'muspari', 'any', 6, 'clear', 'transition', 'improving', 'any', null],
  ["with a shriek like a maddened woman, the banshee wind swirls long spirals of sand and dust into the oppressive heat filtering from the sky", 'muspari', 'any', 6, 'dust', 'transition', 'worsening', 'any', null],
  ["arid kiss of the wind dries the land, intently abrading it with long, firm gusts", 'muspari', 'any', 6, 'clear', 'transition', 'worsening', 'any', null],
  ["biting bits of grit and sand are flung by the malicious wind, blurring the edges of your suddenly impaired and watering vision", 'muspari', 'any', 7, 'dust', 'state', null, 'any', null],
  ["tempo of wind resonates in an undercurrent just below normal hearing, thrumming an ominous low chord beneath dusty skies", 'muspari', 'any', 7, 'clear', 'state', null, 'any', null],
  ["broad sheets of grit are swirled up from the ground, forming fleets of fantasy sand ships fleeing with full sails before the darkening wind", 'muspari', 'any', 7, 'dust', 'state', null, 'any', null],
  ["blinding clouds of sand and grit cloak the sky in a slowly swirling lasso swung by an irritable wind", 'muspari', 'any', 7, 'dust', 'transition', 'improving', 'any', null],
  ["monstrous fist of sand rises ominously from the ground amid screaming winds before lashing out in wild fury", 'muspari', 'any', 7, 'dust', 'transition', 'worsening', 'any', null],
  ["low ominous wail sounding like a bereft woman shudders through the air as the suddenly chill wind batters icy fists against you", 'muspari', 'any', 7, 'clear', 'transition', 'worsening', 'any', null],
  ["wind howls, completely obscuring the horizon in a veil of sand and dust", 'muspari', 'any', 8, 'dust', 'state', null, 'any', null],
  ["severe storm slackens momentarily to a sudden whirlwind of swirling sand", 'muspari', 'any', 8, 'dust', 'transition', 'improving', 'any', null],
  ["harsh patter of sand increases as the wind shrieks, masking everything more than a stone's throw away in a dark cloud of grit", 'muspari', 'any', 8, 'dust', 'transition', 'worsening', 'any', null],
  ["brilliant harsh blue of the sky is innocent of even a suggestion of clouds", 'muspari', 'any', 0, 'clear', 'state', null, 'any', null],
]
